stages:
  data:
    cmd: >-
      python src/sns_mlops/data.py
      --dataset-name NOSIBLE/financial-sentiment
      --output-root data/processed
      --seed 42
      --test-size 0.1
      --val-size 0.1
      --small-size 2000
      --dev-size 10000
    deps:
      - src/sns_mlops/data.py
      - requirements.txt
    outs:
      - data/processed/small
      - data/processed/dev
      - data/processed/full
  train:
    cmd: >-
      python -m sns_mlops.train
      --tier small
      --processed-root data/processed
      --output-dir models/finbert
      --seed 42
      --num-train-epochs 1
      --max-length 64
      --per-device-train-batch-size 4
      --per-device-eval-batch-size 8
      --max-train-samples 64
      --max-eval-samples 64
      --max-test-samples 64
      --save-total-limit 1
      --save-model
      --no-save-checkpoints
    deps:
      - src/sns_mlops/train.py
      - src/sns_mlops/model.py
      - data/processed
      - requirements.txt
    outs:
      - models/finbert/small/run_config.json
      - models/finbert/small/metrics.json
      - models/finbert/small/train.log
